use ash::vk::{Format, ImageAspectFlags};

pub trait FormatExt {
	/// Table mapping [`Format`] to their respective valid [`ImageAspectFlags`].
	///
	/// The giant match is copied from vulkano's autogenerated code and adjusted to work with ash.
	fn aspect(self) -> ImageAspectFlags;
}

impl FormatExt for Format {
	fn aspect(self) -> ImageAspectFlags {
		match self {
			Self::UNDEFINED => ImageAspectFlags::empty(),
			Self::R4G4_UNORM_PACK8 => ImageAspectFlags::COLOR,
			Self::R4G4B4A4_UNORM_PACK16 => ImageAspectFlags::COLOR,
			Self::B4G4R4A4_UNORM_PACK16 => ImageAspectFlags::COLOR,
			Self::R5G6B5_UNORM_PACK16 => ImageAspectFlags::COLOR,
			Self::B5G6R5_UNORM_PACK16 => ImageAspectFlags::COLOR,
			Self::R5G5B5A1_UNORM_PACK16 => ImageAspectFlags::COLOR,
			Self::B5G5R5A1_UNORM_PACK16 => ImageAspectFlags::COLOR,
			Self::A1R5G5B5_UNORM_PACK16 => ImageAspectFlags::COLOR,
			Self::A1B5G5R5_UNORM_PACK16_KHR => ImageAspectFlags::COLOR,
			Self::A8_UNORM_KHR => ImageAspectFlags::COLOR,
			Self::R8_UNORM => ImageAspectFlags::COLOR,
			Self::R8_SNORM => ImageAspectFlags::COLOR,
			Self::R8_USCALED => ImageAspectFlags::COLOR,
			Self::R8_SSCALED => ImageAspectFlags::COLOR,
			Self::R8_UINT => ImageAspectFlags::COLOR,
			Self::R8_SINT => ImageAspectFlags::COLOR,
			Self::R8_SRGB => ImageAspectFlags::COLOR,
			Self::R8G8_UNORM => ImageAspectFlags::COLOR,
			Self::R8G8_SNORM => ImageAspectFlags::COLOR,
			Self::R8G8_USCALED => ImageAspectFlags::COLOR,
			Self::R8G8_SSCALED => ImageAspectFlags::COLOR,
			Self::R8G8_UINT => ImageAspectFlags::COLOR,
			Self::R8G8_SINT => ImageAspectFlags::COLOR,
			Self::R8G8_SRGB => ImageAspectFlags::COLOR,
			Self::R8G8B8_UNORM => ImageAspectFlags::COLOR,
			Self::R8G8B8_SNORM => ImageAspectFlags::COLOR,
			Self::R8G8B8_USCALED => ImageAspectFlags::COLOR,
			Self::R8G8B8_SSCALED => ImageAspectFlags::COLOR,
			Self::R8G8B8_UINT => ImageAspectFlags::COLOR,
			Self::R8G8B8_SINT => ImageAspectFlags::COLOR,
			Self::R8G8B8_SRGB => ImageAspectFlags::COLOR,
			Self::B8G8R8_UNORM => ImageAspectFlags::COLOR,
			Self::B8G8R8_SNORM => ImageAspectFlags::COLOR,
			Self::B8G8R8_USCALED => ImageAspectFlags::COLOR,
			Self::B8G8R8_SSCALED => ImageAspectFlags::COLOR,
			Self::B8G8R8_UINT => ImageAspectFlags::COLOR,
			Self::B8G8R8_SINT => ImageAspectFlags::COLOR,
			Self::B8G8R8_SRGB => ImageAspectFlags::COLOR,
			Self::R8G8B8A8_UNORM => ImageAspectFlags::COLOR,
			Self::R8G8B8A8_SNORM => ImageAspectFlags::COLOR,
			Self::R8G8B8A8_USCALED => ImageAspectFlags::COLOR,
			Self::R8G8B8A8_SSCALED => ImageAspectFlags::COLOR,
			Self::R8G8B8A8_UINT => ImageAspectFlags::COLOR,
			Self::R8G8B8A8_SINT => ImageAspectFlags::COLOR,
			Self::R8G8B8A8_SRGB => ImageAspectFlags::COLOR,
			Self::B8G8R8A8_UNORM => ImageAspectFlags::COLOR,
			Self::B8G8R8A8_SNORM => ImageAspectFlags::COLOR,
			Self::B8G8R8A8_USCALED => ImageAspectFlags::COLOR,
			Self::B8G8R8A8_SSCALED => ImageAspectFlags::COLOR,
			Self::B8G8R8A8_UINT => ImageAspectFlags::COLOR,
			Self::B8G8R8A8_SINT => ImageAspectFlags::COLOR,
			Self::B8G8R8A8_SRGB => ImageAspectFlags::COLOR,
			Self::A8B8G8R8_UNORM_PACK32 => ImageAspectFlags::COLOR,
			Self::A8B8G8R8_SNORM_PACK32 => ImageAspectFlags::COLOR,
			Self::A8B8G8R8_USCALED_PACK32 => ImageAspectFlags::COLOR,
			Self::A8B8G8R8_SSCALED_PACK32 => ImageAspectFlags::COLOR,
			Self::A8B8G8R8_UINT_PACK32 => ImageAspectFlags::COLOR,
			Self::A8B8G8R8_SINT_PACK32 => ImageAspectFlags::COLOR,
			Self::A8B8G8R8_SRGB_PACK32 => ImageAspectFlags::COLOR,
			Self::A2R10G10B10_UNORM_PACK32 => ImageAspectFlags::COLOR,
			Self::A2R10G10B10_SNORM_PACK32 => ImageAspectFlags::COLOR,
			Self::A2R10G10B10_USCALED_PACK32 => ImageAspectFlags::COLOR,
			Self::A2R10G10B10_SSCALED_PACK32 => ImageAspectFlags::COLOR,
			Self::A2R10G10B10_UINT_PACK32 => ImageAspectFlags::COLOR,
			Self::A2R10G10B10_SINT_PACK32 => ImageAspectFlags::COLOR,
			Self::A2B10G10R10_UNORM_PACK32 => ImageAspectFlags::COLOR,
			Self::A2B10G10R10_SNORM_PACK32 => ImageAspectFlags::COLOR,
			Self::A2B10G10R10_USCALED_PACK32 => ImageAspectFlags::COLOR,
			Self::A2B10G10R10_SSCALED_PACK32 => ImageAspectFlags::COLOR,
			Self::A2B10G10R10_UINT_PACK32 => ImageAspectFlags::COLOR,
			Self::A2B10G10R10_SINT_PACK32 => ImageAspectFlags::COLOR,
			Self::R16_UNORM => ImageAspectFlags::COLOR,
			Self::R16_SNORM => ImageAspectFlags::COLOR,
			Self::R16_USCALED => ImageAspectFlags::COLOR,
			Self::R16_SSCALED => ImageAspectFlags::COLOR,
			Self::R16_UINT => ImageAspectFlags::COLOR,
			Self::R16_SINT => ImageAspectFlags::COLOR,
			Self::R16_SFLOAT => ImageAspectFlags::COLOR,
			Self::R16G16_UNORM => ImageAspectFlags::COLOR,
			Self::R16G16_SNORM => ImageAspectFlags::COLOR,
			Self::R16G16_USCALED => ImageAspectFlags::COLOR,
			Self::R16G16_SSCALED => ImageAspectFlags::COLOR,
			Self::R16G16_UINT => ImageAspectFlags::COLOR,
			Self::R16G16_SINT => ImageAspectFlags::COLOR,
			Self::R16G16_SFLOAT => ImageAspectFlags::COLOR,
			Self::R16G16B16_UNORM => ImageAspectFlags::COLOR,
			Self::R16G16B16_SNORM => ImageAspectFlags::COLOR,
			Self::R16G16B16_USCALED => ImageAspectFlags::COLOR,
			Self::R16G16B16_SSCALED => ImageAspectFlags::COLOR,
			Self::R16G16B16_UINT => ImageAspectFlags::COLOR,
			Self::R16G16B16_SINT => ImageAspectFlags::COLOR,
			Self::R16G16B16_SFLOAT => ImageAspectFlags::COLOR,
			Self::R16G16B16A16_UNORM => ImageAspectFlags::COLOR,
			Self::R16G16B16A16_SNORM => ImageAspectFlags::COLOR,
			Self::R16G16B16A16_USCALED => ImageAspectFlags::COLOR,
			Self::R16G16B16A16_SSCALED => ImageAspectFlags::COLOR,
			Self::R16G16B16A16_UINT => ImageAspectFlags::COLOR,
			Self::R16G16B16A16_SINT => ImageAspectFlags::COLOR,
			Self::R16G16B16A16_SFLOAT => ImageAspectFlags::COLOR,
			Self::R32_UINT => ImageAspectFlags::COLOR,
			Self::R32_SINT => ImageAspectFlags::COLOR,
			Self::R32_SFLOAT => ImageAspectFlags::COLOR,
			Self::R32G32_UINT => ImageAspectFlags::COLOR,
			Self::R32G32_SINT => ImageAspectFlags::COLOR,
			Self::R32G32_SFLOAT => ImageAspectFlags::COLOR,
			Self::R32G32B32_UINT => ImageAspectFlags::COLOR,
			Self::R32G32B32_SINT => ImageAspectFlags::COLOR,
			Self::R32G32B32_SFLOAT => ImageAspectFlags::COLOR,
			Self::R32G32B32A32_UINT => ImageAspectFlags::COLOR,
			Self::R32G32B32A32_SINT => ImageAspectFlags::COLOR,
			Self::R32G32B32A32_SFLOAT => ImageAspectFlags::COLOR,
			Self::R64_UINT => ImageAspectFlags::COLOR,
			Self::R64_SINT => ImageAspectFlags::COLOR,
			Self::R64_SFLOAT => ImageAspectFlags::COLOR,
			Self::R64G64_UINT => ImageAspectFlags::COLOR,
			Self::R64G64_SINT => ImageAspectFlags::COLOR,
			Self::R64G64_SFLOAT => ImageAspectFlags::COLOR,
			Self::R64G64B64_UINT => ImageAspectFlags::COLOR,
			Self::R64G64B64_SINT => ImageAspectFlags::COLOR,
			Self::R64G64B64_SFLOAT => ImageAspectFlags::COLOR,
			Self::R64G64B64A64_UINT => ImageAspectFlags::COLOR,
			Self::R64G64B64A64_SINT => ImageAspectFlags::COLOR,
			Self::R64G64B64A64_SFLOAT => ImageAspectFlags::COLOR,
			Self::B10G11R11_UFLOAT_PACK32 => ImageAspectFlags::COLOR,
			Self::E5B9G9R9_UFLOAT_PACK32 => ImageAspectFlags::COLOR,
			Self::D16_UNORM => ImageAspectFlags::DEPTH,
			Self::X8_D24_UNORM_PACK32 => ImageAspectFlags::DEPTH,
			Self::D32_SFLOAT => ImageAspectFlags::DEPTH,
			Self::S8_UINT => ImageAspectFlags::STENCIL,
			Self::D16_UNORM_S8_UINT => ImageAspectFlags::DEPTH | ImageAspectFlags::STENCIL,
			Self::D24_UNORM_S8_UINT => ImageAspectFlags::DEPTH | ImageAspectFlags::STENCIL,
			Self::D32_SFLOAT_S8_UINT => ImageAspectFlags::DEPTH | ImageAspectFlags::STENCIL,
			Self::BC1_RGB_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::BC1_RGB_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::BC1_RGBA_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::BC1_RGBA_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::BC2_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::BC2_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::BC3_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::BC3_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::BC4_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::BC4_SNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::BC5_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::BC5_SNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::BC6H_UFLOAT_BLOCK => ImageAspectFlags::COLOR,
			Self::BC6H_SFLOAT_BLOCK => ImageAspectFlags::COLOR,
			Self::BC7_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::BC7_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::ETC2_R8G8B8_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::ETC2_R8G8B8_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::ETC2_R8G8B8A1_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::ETC2_R8G8B8A1_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::ETC2_R8G8B8A8_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::ETC2_R8G8B8A8_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::EAC_R11_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::EAC_R11_SNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::EAC_R11G11_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::EAC_R11G11_SNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_4X4_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_4X4_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_5X4_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_5X4_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_5X5_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_5X5_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_6X5_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_6X5_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_6X6_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_6X6_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_8X5_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_8X5_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_8X6_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_8X6_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_8X8_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_8X8_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_10X5_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_10X5_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_10X6_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_10X6_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_10X8_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_10X8_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_10X10_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_10X10_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_12X10_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_12X10_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_12X12_UNORM_BLOCK => ImageAspectFlags::COLOR,
			Self::ASTC_12X12_SRGB_BLOCK => ImageAspectFlags::COLOR,
			Self::G8B8G8R8_422_UNORM => ImageAspectFlags::COLOR,
			Self::B8G8R8G8_422_UNORM => ImageAspectFlags::COLOR,
			Self::G8_B8_R8_3PLANE_420_UNORM => {
				ImageAspectFlags::COLOR
					| ImageAspectFlags::PLANE_0
					| ImageAspectFlags::PLANE_1
					| ImageAspectFlags::PLANE_2
			}
			Self::G8_B8R8_2PLANE_420_UNORM => {
				ImageAspectFlags::COLOR | ImageAspectFlags::PLANE_0 | ImageAspectFlags::PLANE_1
			}
			Self::G8_B8_R8_3PLANE_422_UNORM => {
				ImageAspectFlags::COLOR
					| ImageAspectFlags::PLANE_0
					| ImageAspectFlags::PLANE_1
					| ImageAspectFlags::PLANE_2
			}
			Self::G8_B8R8_2PLANE_422_UNORM => {
				ImageAspectFlags::COLOR | ImageAspectFlags::PLANE_0 | ImageAspectFlags::PLANE_1
			}
			Self::G8_B8_R8_3PLANE_444_UNORM => {
				ImageAspectFlags::COLOR
					| ImageAspectFlags::PLANE_0
					| ImageAspectFlags::PLANE_1
					| ImageAspectFlags::PLANE_2
			}
			Self::R10X6_UNORM_PACK16 => ImageAspectFlags::COLOR,
			Self::R10X6G10X6_UNORM_2PACK16 => ImageAspectFlags::COLOR,
			Self::R10X6G10X6B10X6A10X6_UNORM_4PACK16 => ImageAspectFlags::COLOR,
			Self::G10X6B10X6G10X6R10X6_422_UNORM_4PACK16 => ImageAspectFlags::COLOR,
			Self::B10X6G10X6R10X6G10X6_422_UNORM_4PACK16 => ImageAspectFlags::COLOR,
			Self::G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16 => {
				ImageAspectFlags::COLOR
					| ImageAspectFlags::PLANE_0
					| ImageAspectFlags::PLANE_1
					| ImageAspectFlags::PLANE_2
			}
			Self::G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16 => {
				ImageAspectFlags::COLOR | ImageAspectFlags::PLANE_0 | ImageAspectFlags::PLANE_1
			}
			Self::G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16 => {
				ImageAspectFlags::COLOR
					| ImageAspectFlags::PLANE_0
					| ImageAspectFlags::PLANE_1
					| ImageAspectFlags::PLANE_2
			}
			Self::G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16 => {
				ImageAspectFlags::COLOR | ImageAspectFlags::PLANE_0 | ImageAspectFlags::PLANE_1
			}
			Self::G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16 => {
				ImageAspectFlags::COLOR
					| ImageAspectFlags::PLANE_0
					| ImageAspectFlags::PLANE_1
					| ImageAspectFlags::PLANE_2
			}
			Self::R12X4_UNORM_PACK16 => ImageAspectFlags::COLOR,
			Self::R12X4G12X4_UNORM_2PACK16 => ImageAspectFlags::COLOR,
			Self::R12X4G12X4B12X4A12X4_UNORM_4PACK16 => ImageAspectFlags::COLOR,
			Self::G12X4B12X4G12X4R12X4_422_UNORM_4PACK16 => ImageAspectFlags::COLOR,
			Self::B12X4G12X4R12X4G12X4_422_UNORM_4PACK16 => ImageAspectFlags::COLOR,
			Self::G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16 => {
				ImageAspectFlags::COLOR
					| ImageAspectFlags::PLANE_0
					| ImageAspectFlags::PLANE_1
					| ImageAspectFlags::PLANE_2
			}
			Self::G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16 => {
				ImageAspectFlags::COLOR | ImageAspectFlags::PLANE_0 | ImageAspectFlags::PLANE_1
			}
			Self::G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16 => {
				ImageAspectFlags::COLOR
					| ImageAspectFlags::PLANE_0
					| ImageAspectFlags::PLANE_1
					| ImageAspectFlags::PLANE_2
			}
			Self::G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16 => {
				ImageAspectFlags::COLOR | ImageAspectFlags::PLANE_0 | ImageAspectFlags::PLANE_1
			}
			Self::G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16 => {
				ImageAspectFlags::COLOR
					| ImageAspectFlags::PLANE_0
					| ImageAspectFlags::PLANE_1
					| ImageAspectFlags::PLANE_2
			}
			Self::G16B16G16R16_422_UNORM => ImageAspectFlags::COLOR,
			Self::B16G16R16G16_422_UNORM => ImageAspectFlags::COLOR,
			Self::G16_B16_R16_3PLANE_420_UNORM => {
				ImageAspectFlags::COLOR
					| ImageAspectFlags::PLANE_0
					| ImageAspectFlags::PLANE_1
					| ImageAspectFlags::PLANE_2
			}
			Self::G16_B16R16_2PLANE_420_UNORM => {
				ImageAspectFlags::COLOR | ImageAspectFlags::PLANE_0 | ImageAspectFlags::PLANE_1
			}
			Self::G16_B16_R16_3PLANE_422_UNORM => {
				ImageAspectFlags::COLOR
					| ImageAspectFlags::PLANE_0
					| ImageAspectFlags::PLANE_1
					| ImageAspectFlags::PLANE_2
			}
			Self::G16_B16R16_2PLANE_422_UNORM => {
				ImageAspectFlags::COLOR | ImageAspectFlags::PLANE_0 | ImageAspectFlags::PLANE_1
			}
			Self::G16_B16_R16_3PLANE_444_UNORM => {
				ImageAspectFlags::COLOR
					| ImageAspectFlags::PLANE_0
					| ImageAspectFlags::PLANE_1
					| ImageAspectFlags::PLANE_2
			}
			Self::PVRTC1_2BPP_UNORM_BLOCK_IMG => ImageAspectFlags::COLOR,
			Self::PVRTC1_4BPP_UNORM_BLOCK_IMG => ImageAspectFlags::COLOR,
			Self::PVRTC2_2BPP_UNORM_BLOCK_IMG => ImageAspectFlags::COLOR,
			Self::PVRTC2_4BPP_UNORM_BLOCK_IMG => ImageAspectFlags::COLOR,
			Self::PVRTC1_2BPP_SRGB_BLOCK_IMG => ImageAspectFlags::COLOR,
			Self::PVRTC1_4BPP_SRGB_BLOCK_IMG => ImageAspectFlags::COLOR,
			Self::PVRTC2_2BPP_SRGB_BLOCK_IMG => ImageAspectFlags::COLOR,
			Self::PVRTC2_4BPP_SRGB_BLOCK_IMG => ImageAspectFlags::COLOR,
			Self::ASTC_4X4_SFLOAT_BLOCK_EXT => ImageAspectFlags::COLOR,
			Self::ASTC_5X4_SFLOAT_BLOCK_EXT => ImageAspectFlags::COLOR,
			Self::ASTC_5X5_SFLOAT_BLOCK_EXT => ImageAspectFlags::COLOR,
			Self::ASTC_6X5_SFLOAT_BLOCK_EXT => ImageAspectFlags::COLOR,
			Self::ASTC_6X6_SFLOAT_BLOCK_EXT => ImageAspectFlags::COLOR,
			Self::ASTC_8X5_SFLOAT_BLOCK_EXT => ImageAspectFlags::COLOR,
			Self::ASTC_8X6_SFLOAT_BLOCK_EXT => ImageAspectFlags::COLOR,
			Self::ASTC_8X8_SFLOAT_BLOCK_EXT => ImageAspectFlags::COLOR,
			Self::ASTC_10X5_SFLOAT_BLOCK_EXT => ImageAspectFlags::COLOR,
			Self::ASTC_10X6_SFLOAT_BLOCK_EXT => ImageAspectFlags::COLOR,
			Self::ASTC_10X8_SFLOAT_BLOCK_EXT => ImageAspectFlags::COLOR,
			Self::ASTC_10X10_SFLOAT_BLOCK_EXT => ImageAspectFlags::COLOR,
			Self::ASTC_12X10_SFLOAT_BLOCK_EXT => ImageAspectFlags::COLOR,
			Self::ASTC_12X12_SFLOAT_BLOCK_EXT => ImageAspectFlags::COLOR,
			Self::G8_B8R8_2PLANE_444_UNORM => {
				ImageAspectFlags::COLOR | ImageAspectFlags::PLANE_0 | ImageAspectFlags::PLANE_1
			}
			Self::G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16 => {
				ImageAspectFlags::COLOR | ImageAspectFlags::PLANE_0 | ImageAspectFlags::PLANE_1
			}
			Self::G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16 => {
				ImageAspectFlags::COLOR | ImageAspectFlags::PLANE_0 | ImageAspectFlags::PLANE_1
			}
			Self::G16_B16R16_2PLANE_444_UNORM => {
				ImageAspectFlags::COLOR | ImageAspectFlags::PLANE_0 | ImageAspectFlags::PLANE_1
			}
			Self::A4R4G4B4_UNORM_PACK16 => ImageAspectFlags::COLOR,
			Self::A4B4G4R4_UNORM_PACK16 => ImageAspectFlags::COLOR,
			Self::R16G16_S10_5_NV => ImageAspectFlags::COLOR,
			_ => unreachable!("invalid format"),
		}
	}
}
